
pc2cbm /port=lpt1 /address=2048 chr\1a.chr 1a.0
pc2cbm /port=lpt1 /address=32768 blk\1a.blk 1a.1
pc2cbm /port=lpt1 /address=16384 map\1a.map 1a.2
pc2cbm /port=lpt1 /address=4096 1a 1a.3
pc2cbm /port=lpt1 /address=4352 col\1a.col 1a.4

pc2cbm /port=lpt1 /address=2048 chr\1b.chr 1b.0
pc2cbm /port=lpt1 /address=32768 blk\1b.blk 1b.1
pc2cbm /port=lpt1 /address=16384 map\1b.map 1b.2
pc2cbm /port=lpt1 /address=4096 1b 1b.3
pc2cbm /port=lpt1 /address=4352 col\1b.col 1b.4

pc2cbm /port=lpt1 /address=2048 chr\2a.chr 2a.0
pc2cbm /port=lpt1 /address=32768 blk\2a.blk 2a.1
pc2cbm /port=lpt1 /address=16384 map\2a.map 2a.2
pc2cbm /port=lpt1 /address=4096 2a 2a.3
pc2cbm /port=lpt1 /address=4352 col\2a.col 2a.4

pc2cbm /port=lpt1 /address=2048 chr\2b.chr 2b.0
pc2cbm /port=lpt1 /address=32768 blk\2b.blk 2b.1
pc2cbm /port=lpt1 /address=16384 map\2b.map 2b.2
pc2cbm /port=lpt1 /address=4096 2b 2b.3
pc2cbm /port=lpt1 /address=4352 col\2b.col 2b.4

pc2cbm /port=lpt1 /address=2048 chr\2c.chr 2c.0
pc2cbm /port=lpt1 /address=32768 blk\2c.blk 2c.1
pc2cbm /port=lpt1 /address=16384 map\2c.map 2c.2
pc2cbm /port=lpt1 /address=4096 2c 2c.3
pc2cbm /port=lpt1 /address=4352 col\2c.col 2c.4

pc2cbm /port=lpt1 /address=2048 chr\3a.chr 3a.0
pc2cbm /port=lpt1 /address=32768 blk\3a.blk 3a.1
pc2cbm /port=lpt1 /address=16384 map\3a.map 3a.2
pc2cbm /port=lpt1 /address=4096 3a 3a.3
pc2cbm /port=lpt1 /address=4352 col\3a.col 3a.4

pc2cbm /port=lpt1 /address=2048 chr\3b.chr 3b.0
pc2cbm /port=lpt1 /address=32768 blk\3b.blk 3b.1
pc2cbm /port=lpt1 /address=16384 map\3b.map 3b.2
pc2cbm /port=lpt1 /address=4096 3b 3b.3
pc2cbm /port=lpt1 /address=4352 col\3b.col 3b.4

pc2cbm /port=lpt1 /address=2048 chr\3c.chr 3c.0
pc2cbm /port=lpt1 /address=32768 blk\3c.blk 3c.1
pc2cbm /port=lpt1 /address=16384 map\3c.map 3c.2
pc2cbm /port=lpt1 /address=4096 3c 3c.3
pc2cbm /port=lpt1 /address=4352 col\3c.col 3c.4

pc2cbm /port=lpt1 /address=2048 chr\4a.chr 4a.0
pc2cbm /port=lpt1 /address=32768 blk\4a.blk 4a.1
pc2cbm /port=lpt1 /address=16384 map\4a.map 4a.2
pc2cbm /port=lpt1 /address=4096 4a 4a.3
pc2cbm /port=lpt1 /address=4352 col\4a.col 4a.4

pc2cbm /port=lpt1 /address=2048 chr\4b.chr 4b.0
pc2cbm /port=lpt1 /address=32768 blk\4b.blk 4b.1
pc2cbm /port=lpt1 /address=16384 map\4b.map 4b.2
pc2cbm /port=lpt1 /address=4096 4b 4b.3
pc2cbm /port=lpt1 /address=4352 col\4b.col 4b.4

pc2cbm /port=lpt1 /address=2048 chr\4c.chr 4c.0
pc2cbm /port=lpt1 /address=32768 blk\4c.blk 4c.1
pc2cbm /port=lpt1 /address=16384 map\4c.map 4c.2
pc2cbm /port=lpt1 /address=4096 4c 4c.3
pc2cbm /port=lpt1 /address=4352 col\4c.col 4c.4

pc2cbm /port=lpt1 /address=2048 chr\5.chr 5.0
pc2cbm /port=lpt1 /address=32768 blk\5.blk 5.1
pc2cbm /port=lpt1 /address=16384 map\5.map 5.2
pc2cbm /port=lpt1 /address=4096 5 5.3
pc2cbm /port=lpt1 /address=4352 col\5.col 5.4

