@ECHO Disk Side Two PAL & NTSC
pc2cbm /port=lpt1 /address=512 BANK0.DAT B0
pc2cbm /port=lpt1 /address=512 BANK1.DAT B1
pc2cbm /port=lpt1 /address=512 BANK2.DAT B2
pc2cbm /port=lpt1 /address=512 BANK3.DAT B3
pc2cbm /port=lpt1 /address=512 BANK4.DAT B4
pc2cbm /port=lpt1 /address=512 BANK6.DAT B6
pc2cbm /port=lpt1 /address=512 BANK7.DAT B7

pc2cbm /port=lpt1 /address=34560 LA.DAT LA
pc2cbm /port=lpt1 /address=63488 GA.CHR GA

pc2cbm /port=lpt1 /address=34560 LB.DAT LB
pc2cbm /port=lpt1 /address=63488 GB.CHR GB

pc2cbm /port=lpt1 /address=34560 LC.DAT LC
pc2cbm /port=lpt1 /address=63488 GC.CHR GC

pc2cbm /port=lpt1 /address=34560 LD.DAT LD
pc2cbm /port=lpt1 /address=63488 GD.CHR GD

pc2cbm /port=lpt1 /address=34560 LE.DAT LE
pc2cbm /port=lpt1 /address=63488 GE.CHR GE

pc2cbm /port=lpt1 /address=34560 LF.DAT LF
pc2cbm /port=lpt1 /address=63488 GF.CHR GF

pc2cbm /port=lpt1 /address=34560 LG.DAT LG
pc2cbm /port=lpt1 /address=63488 GG.CHR GG

pc2cbm /port=lpt1 /address=34560 LH.DAT LH
pc2cbm /port=lpt1 /address=63488 GH.CHR GH

pc2cbm /port=lpt1 /address=34560 LI.DAT LI
pc2cbm /port=lpt1 /address=63488 GI.CHR GI

pc2cbm /port=lpt1 /address=34560 LJ.DAT LJ
pc2cbm /port=lpt1 /address=63488 GJ.CHR GJ

pc2cbm /port=lpt1 /address=34560 LK.DAT LK
pc2cbm /port=lpt1 /address=63488 GK.CHR GK

pc2cbm /port=lpt1 /address=34560 LL.DAT LL
pc2cbm /port=lpt1 /address=63488 GL.CHR GL

pc2cbm /port=lpt1 /address=34560 LM.DAT LM
pc2cbm /port=lpt1 /address=63488 GM.CHR GM

pc2cbm /port=lpt1 /address=34560 LN.DAT LN
pc2cbm /port=lpt1 /address=63488 GN.CHR GN

pc2cbm /port=lpt1 /address=34560 LO.DAT LO
pc2cbm /port=lpt1 /address=63488 GO.CHR GO

pc2cbm /port=lpt1 /address=34560 LP.DAT LP
pc2cbm /port=lpt1 /address=63488 GP.CHR GP

